name: HarvestCLI
services:

  cli:
    image: cloud-harvest-cli:latest
    build:
      dockerfile: Dockerfile
      ssh:
        - default
    environment:
      - "TERM=xterm-256color"
    stdin_open: true
    tty: true
    volumes:
      -
      - "~/.ssh:/root/.ssh"
      - "./app/:/src/app/"
    working_dir: /src
    user: "${UID}:${GID}"
