# Gives users the ability to install plugins for different services, such as cloud services providers (AWS) and
# databases, such as MySQL, PostgreSQL, or Microsoft SQL Server.

.schema:
  version: 2024.01.09

path: ~/.harvest/cli/plugins
repos:
#  - source: ""
#    label: main
